### DISCUSSION TITLE
Implementation challenges: x-correlator

### DISCUSSION THREAD

**Discussion by StefanoFalsetto-CKHIOD** [camaraproject/CallForwardingSignal#108] [General]
The format of x-correlator header is not clearly defined in YAML. For security reasons, it is better to clearly define it.
In Camara API Design Guidelines there is an example using an UUID, but it is not clear Which version of UUID should be used. 

What should we use? UUIDv3? UUIDv5?

**Comment by FabrizioMoggio** [comment]
I'm not sure about the issue. In my understanding the value for x-correlator is chosen by the API Consumer. For the API Producer it is a String.

From the Guidelines:
"When the API Consumer includes the "x-correlator" header in the request, the API provider must include it in the response with the same value that was used in the request."

**Comment by StefanoFalsetto-CKHIOD** [comment]
I agree with you, this value is chosen by the API Consumer. 
But, from a security point of view, it is better for an API Producer to know the details of data it is receiving. For example: which is the maximum length of this string? Which is the set of characters allowed? 
We could answer to this questions just telling: the x-correlator **must be** (i.e., the opposite of _recommended_) an UUID.
A nice to have information could be which version of UUID is recommended.

**Reply by FabrizioMoggio** [reply]
Do you mean a sort of recommendation we include in the API documentation? Without making it mandatory, right?

**Reply by StefanoFalsetto-CKHIOD** [reply]
I mean adding to the x-correlator definition something like the following (I changed the description and added the string format). 

```
x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services. Must be an UUID.
      schema:
           type: string
           format: uuid
```

Nice to have, if all of us thinks is relevant, we could also add to the description the recommended (not mandatory) version of UUID.
